/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'Saree' : null } |
  { 'Kameez' : null } |
  { 'Salwar' : null } |
  { 'Kurti' : null } |
  { 'Dupatta' : null } |
  { 'Other' : null } |
  { 'Lehenga' : null };
export interface ContactMessage {
  'id' : bigint,
  'name' : string,
  'createdAt' : Timestamp,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export type ExternalBlob = Uint8Array;
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'shopId' : bigint,
  'createdAt' : bigint,
  'productId' : bigint,
  'totalAmount' : bigint,
  'buyerPrincipal' : [] | [Principal],
  'quantity' : bigint,
  'buyerName' : string,
  'stripeSessionId' : string,
}
export type OrderId = bigint;
export interface OrderInput {
  'shopId' : bigint,
  'productId' : bigint,
  'quantity' : bigint,
  'buyerName' : string,
}
export type OrderStatus = { 'Paid' : null } |
  { 'Cancelled' : null } |
  { 'Pending' : null };
export interface Product {
  'id' : ProductId,
  'shopId' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'stock' : bigint,
  'imageKey' : ExternalBlob,
  'category' : Category,
  'price' : bigint,
}
export type ProductId = bigint;
export interface ProductInput {
  'shopId' : bigint,
  'name' : string,
  'description' : string,
  'stock' : bigint,
  'imageKey' : ExternalBlob,
  'category' : Category,
  'price' : bigint,
}
export interface Shop {
  'id' : ShopId,
  'ownerId' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'whatsappNumber' : string,
  'phone' : string,
  'location' : string,
}
export type ShopId = bigint;
export interface ShopInput {
  'name' : string,
  'description' : string,
  'whatsappNumber' : string,
  'phone' : string,
  'location' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addProduct' : ActorMethod<[ProductInput], Product>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createOrder' : ActorMethod<[OrderInput, string, string], string>,
  'createShop' : ActorMethod<[ShopInput], Shop>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllShops' : ActorMethod<[], Array<Shop>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getMyShop' : ActorMethod<[], [] | [Shop]>,
  'getProductById' : ActorMethod<[bigint], [] | [Product]>,
  'getShopById' : ActorMethod<[bigint], [] | [Shop]>,
  'getShopProducts' : ActorMethod<[bigint], Array<Product>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'searchProducts' : ActorMethod<
    [string, [] | [Category], [] | [bigint], [] | [bigint]],
    Array<Product>
  >,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitContactForm' : ActorMethod<
    [string, string, string, string],
    { 'ok' : ContactMessage } |
      { 'err' : string }
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], Order>,
  'updateProduct' : ActorMethod<[bigint, ProductInput], Product>,
  'updateShop' : ActorMethod<[bigint, ShopInput], Shop>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];